### PR TITLE
ColorParams

### PR DESCRIPTION
**Pull request by Syntax-Sculptor**

### CODE REVIEW

**Comment by Zamiell** [comment]
in the future, remember that the constructor should come first so that it matches the prior art

**Comment by Zamiell** [comment]
also remember to add the repentogon jsdoc

**Comment by Zamiell** [comment]
also it looks likeColorParams.d.ts was not in the "classes" directory

**Comment by Syntax-Sculptor** [comment]
Will be fixed 👍

**Comment by Zamiell** [comment]
i fixed it already for these

**Comment by Zamiell** [comment]
https://github.com/IsaacScript/isaacscript/commit/bd6efd9fbf65f2197c5825ad967f487e195dab7e

**Pull request merged**
