### PR TITLE
Capsule Class

### PR DESCRIPTION
**Pull request by Syntax-Sculptor**

### CODE REVIEW

**Comment by Zamiell** [comment]
can we move all of the repentagon-only classes into a directory called `isaac-typescript-definitions-repentogon`?

**Comment by Syntax-Sculptor** [comment]
> can we move all of the repentagon-only classes into a directory called `isaac-typescript-definitions-repentogon`?

Sure. I'm assuming the directory would still be under `types`?

**Comment by Zamiell** [comment]
no, i meant like a new package in the monorepo

./packages/isaac-typescript-definitions-repentagon/src/types/foo

and then we can move the repentagon-only enums there too

**Comment by Zamiell** [comment]
and this would be published to npm as `isaac-typescript-definitions-repentagon`

**Comment by Syntax-Sculptor** [comment]
Would be a good idea.

**Comment by Zamiell** [comment]
the reason is because right now, vanilla users would be able to type `Capsule()`, and then wouldn't get an error, which is bad

**Pull request merged**
