### PR TITLE
fix(defs): Change module from ESM to CJS

### LINKED ISSUE #63: `isaac-typescript-definitions` export ESM files instead of CJS ones
`isaac-typescript-definitions` export ESM files despite having `"type": "commonjs"` in the `package.json`. Because of that, JS tools (like `vitest`) cannot properly import this package.

### PR DESCRIPTION
**Pull request by aleksander-ciesielski**
Fixes #63

### CODE REVIEW

**Comment by Zamiell** [comment]
hi, thanks for the pr.
vitest can run ESM right?

**Comment by aleksander-ciesielski** [comment]
yes, but if we provide ESM out files (like currently), then the package should be marked as `"type": "module"` in the `package.json`. Currently we have ESM files but we say that they're CJS, so vitest fails to import them (unexpected keyword `export` or smth). There are two options to fix it:
  * change the TypeScript configuration to output CJS files (this PR does exactly this)
  * change the `type` field in `package.json` from `"commonjs"` to `"module"`

I guess either option works so it's up to your preference

**Comment by Zamiell** [comment]
ok sounds good, ill take a look at it tomorrow

**Comment by Zamiell** [comment]
im working on converting a bunch of things in the repo to ESM over on the `dist` branch, if i finish and everything looks good then we might not need this PR, but i'll let you know later

**Comment by aleksander-ciesielski** [comment]
sure, I see that you already merged your changes. waiting for the release to check if it can be imported properly now 🙂

**Comment by Zamiell** [comment]
yeah ive been working on this all week, im gonna try to get CI to pass first and then i'll mess with trying a release

**Comment by Zamiell** [comment]
I got CI passing today, i am going to release a new version of the CLI first and see if it still works under ESM

**Comment by Zamiell** [comment]
should be fixed in version 37.3.1

**Pull request closed without merging**
