### PR TITLE
Change type guards for AddCallback and AddPriorityCallback

### LINKED ISSUE #52: There's no way to extend ModCallback enum for custom typed callbacks.
Isaac API supports custom callbacks, although in IsaacScript there's no way to extend it as it's tied to `ModCallback` enum, which isn't extensible in TypeScript:

```ts
AddCallback<T extends ModCallback | string>(
  modCallback: T,
  ...args: T extends ModCallback ? AddCallbackParameters[T] : unknown[]
): void;
```
Declaring a new overload for `AddCallback` isn't an option either, as the base signature will always be picked over the new one. A way to fix this issue is to change the guard of `T` to `keyof AddCallbackParameters`, which would allow adding custom callbacks by augmenting `AddCallbackParameters` interface:

```ts
declare "isaac-typescript-definitions" {
  interface AddCallbackParameters {
    MY_CUSTOM_CALLBACK: [(param: boolean) => string];
  }
}
```

### PR DESCRIPTION
**Pull request by aleksander-ciesielski**
Fixes #52

### CODE REVIEW

**Comment by Zamiell** [comment]
you forgot Isaac.AddPriorityCallback

**Comment by Zamiell** [comment]
also this pull request doesn't pass CI

**Comment by aleksander-ciesielski** [comment]
CI is failing because `isaacscript-common` is using `isaac-typescript-definitions` from npm instead of local package.

**Comment by Zamiell** [comment]
ok, i'll publish a new version, thanks

**Pull request merged**
