### PR TITLE
Repentogon type fixes

### PR DESCRIPTION
**Pull request by Syntax-Sculptor**

### CODE REVIEW

**Comment by Zamiell** [comment]
i think adding another entry to ActiveEnum will mess things up, because unions will no longer be complete in isaacscript-common.
is that a necessary change?

**Comment by Syntax-Sculptor** [comment]
> i think adding another entry to ActiveEnum will mess things up, because unions will no longer be complete in isaacscript-common. is that a necessary change?

This change was made as -1 could be returned by `EntityPlayer.GetActiveItemSlot` but if that has the potential to mess things up, I suppose people can just cast -1 to `ActiveSlot`.

**Comment by Zamiell** [comment]
then change the return type of `EntityPlayer.GetActiveItemSlot` to `ActiveSlot | -1`.

**Comment by Zamiell** [comment]
(and document in the jsdoc of the function that -1 means no active slot)

**Comment by Zamiell** [comment]
and btw this is a good change because it forces type narrowing in mods

**Pull request merged**
